### ISSUE TITLE
Test shipped assemblies are compiled ahead-of-time

### ISSUE THREAD

**Issue by tmds** [redhat-developer/dotnet-regular-tests#103]
With 3.0 and 3.1 servicing some assemblies are no longer being compiled ahead-of-time (https://bugzilla.redhat.com/show_bug.cgi?id=1791462, https://github.com/dotnet/source-build/issues/1452).

We should add a test to detect regressions.

We already have a test that looks into the assemblies: https://github.com/redhat-developer/dotnet-regular-tests/blob/master/dlls-in-release-mode/check-ngen-dlls. This test is written in Python. We may want to build further on that.

Alternatively, we can check using C#:
```cs
using System;
using System.IO;
using System.Reflection.PortableExecutable;

namespace console
{
    class Program
    {
        const int LINUX_IMAGE_FILE_MACHINE_NATIVE_OS_OVERRIDE = 0x7B79;

        static void Main(string[] args)
        {
            string assembly = args[0];

            PEReader reader = new PEReader(File.OpenRead(assembly));
            var managedNativeDirectoryHeader = reader.PEHeaders.CorHeader.ManagedNativeHeaderDirectory;
            bool r2r = managedNativeDirectoryHeader.Size != 0;
            Console.WriteLine($"R2R: {r2r}");
            if (r2r)
            {
                Machine machine = reader.PEHeaders.CoffHeader.Machine;
                Machine linuxArch = (Machine)((int)machine ^ LINUX_IMAGE_FILE_MACHINE_NATIVE_OS_OVERRIDE);
                Console.WriteLine($"Linux arch: {linuxArch}");
            }
        }
    }
}
```

Or maybe we want to combine both tests, and write them in C#?

I don't speak Python.

cc @omajid @RheaAyase

**Comment by omajid** [comment]
I think we need to combine both tests into a single test that checks all our assemblies are valid. Written in C# itself.

Any thoughts or preferences @aslicerh and @RheaAyase ?

**Comment by omajid** [comment]
A couple of questions:

- At least some `.dll` files (eg `System.Private.CoreLib.dll` in 2.1) have a `ManagedNativeHeader` that points to a `NGEN` header (that's what `check-ngen-dlls` looks at) instead of `R2R` header. Is it safe to ignore those?

- Which assemblies are supposed to be ready-to-run compiled?
  - All `.dll` files, even `.resource.dll` files?
  - Targeting packs?
  - Reference packages?
  - SDK tools?
  - Shared framework?
    - `mscorlib.dll`?
    - `System.Runtime.Windows.dll`?

**Comment by tmds** [comment]
@omajid, have a look at what Microsoft assemblies are r2r compiled and derive the list from that.
