### ISSUE TITLE
add tests for 'dotnet tool'

### ISSUE THREAD

**Issue by tmds** [redhat-developer/dotnet-regular-tests#12]
This is new in 2.1. It may have some quirks on source-build .NET Core.

**Comment by RheaAyase** [comment]
ref issue: https://bugzilla.redhat.com/show_bug.cgi?id=1584525

**Comment by RheaAyase** [comment]
[done](https://github.com/redhat-developer/dotnet-regular-tests/commit/646965102838e07cbfd38b5fca380148fb94bc89)
