### ISSUE TITLE
Add a test for dynamic PGO being enabled

### ISSUE THREAD

**Issue by omajid** [redhat-developer/dotnet-regular-tests#152]
See https://github.com/dotnet/runtime/blob/main/docs/design/features/DynamicPgo.md

It was implemented in .NET 6. We need to make sure it's enabled and working in source-build

**Comment by omajid** [comment]
Fixed by https://github.com/redhat-developer/dotnet-regular-tests/pull/279

**Comment by tmds** [comment]
@omajid just wondering: do you think there is something specific to source-build that would cause dynamic pgo to fail with our build, and not with Microsoft's?

**Comment by omajid** [comment]
When I last talked to Microsoft runtime folks, they weren't sure that dynamic PGO is even supported/working in source-build builds. I figured we should test that it's enabled and working and doesn't regress.

Related, static PGO is available on Microsoft's builds, which makes me want to ensure that at least dynamic PGO is working on source-build.

**Comment by tmds** [comment]
> they weren't sure that dynamic PGO is even supported/working in source-build builds

Oh, I haven't looked at the implementation. I assumed it would be all in the .NET JIT, and therefore not likely to differ in behavior between source-built and Microsoft built.
