### ISSUE TITLE
http/curl tests often fail due to server/network issues

### ISSUE THREAD

**Issue by RheaAyase** [redhat-developer/dotnet-regular-tests#21]
It would be worth thinking about also running server as a test and testing against that, to prevent network issues.

**Comment by tmds** [comment]
Fetching nuget packages by dotnet restore should handle this to some extent, otherwise it would cause major issues for anyone running dotnet restore.
Is there some specific things that fail often for our tests?

**Comment by RheaAyase** [comment]
It's not about nuget, it's about e.g. rest-client test, where it tries to get some stuff from 3rd party server. There is one more test (curl one? I don't remember) that tries to fetch some stuff from github. Both of these regularly fail with errors like 403, etc... Some of it probably caused by too many requests from us, so they time it out, etc...

**Comment by RheaAyase** [comment]
...so i'm thinking that these tests should first spawn their own server they could test against, or we can have one running internally permanently.

**Comment by RheaAyase** [comment]
`rest-client` was disabled for due to this issue...

**Comment by tmds** [comment]
> i'm thinking that these tests should first spawn their own server they could test against,

Makes sense.

**Comment by tmds** [comment]
I'm assume we no longer have this issue.
