### ISSUE TITLE
Support running against vmr output

### ISSUE THREAD

**Issue by tmds** [redhat-developer/dotnet-regular-tests#235]
Some of these tests are meant to be ran against a released version of .NET that is installed on the system.

It would be nice if we add a way of skipping those, so the remaining tests can be used in daily runs against the vmr output.

cc @omajid

**Comment by omajid** [comment]
If tests can be run against the VMR output, perhaps they should be added to the VMR test suite itself? That would shift testing further left and reduce surprises as we get closer to the release.

I don't know if that's doable for all/many of our tests, though. Some of them get pretty OS/environment specific. So this would be quite nice to have.
