### ISSUE TITLE
Tests should treat project build warnings as errors

### ISSUE THREAD

**Issue by omajid** [redhat-developer/dotnet-regular-tests#25]
There has been a few cases where .NET Core template projects (eg, `dotnet new console`, `dotnet new classlib`) were producing warnings during build. These warnings are generally symptomatic of some other bug within .NET Core. But these regular tests aren't flagging the warnings as error.

For one example, see https://github.com/redhat-developer/s2i-dotnetcore/issues/221

**Comment by RheaAyase** [comment]
ack, already on the (long) todo list...

**Comment by omajid** [comment]
cc @tmds 

This would have caught the netstandard.library version issues, I think.

**Comment by tmds** [comment]
We need to add a netstandard library to dotnet-regular-tests to cover the issue. We aren't using a netstandardx.y target in the existing projects.

**Comment by omajid** [comment]
Hm. I seem to remember zzambers had a test that was exercising all `dotnet foo` targets. What happened to that test?

**Comment by tmds** [comment]
Ah, maybe one is generated as part of the tests. I just grepped the repo.

**Comment by omajid** [comment]
It looks like we lost the test at some point. I just spoke to @RheaAyase on IRC who has agreed to add those tests back.

**Comment by RheaAyase** [comment]
As Tom said, this would not cover it because we have no tests that use/make/whatever netstandard library... We need a few more copies of _me_ to work on tests.

**Comment by tmds** [comment]
@RheaAyase can you re-open this issue? You may have time later or someone else can pick it up.

**Comment by RheaAyase** [comment]
And there is no reasonable way to apply this in a generic way to the tests that create their own project files (e.g. template test) - it is responsibility of each test to handle it...

**Comment by tmds** [comment]
Ah. It wasn't clear for me that you had updated some tests.
You could do something like this:
```
dotnet new <template> --no-restore
dotnet build /p:TreatWarningsAsErrors=true
```

**Comment by RheaAyase** [comment]
That still isn't generic and every single test has to change the way it builds it... Same difference really.

**Comment by tmds** [comment]
fyi, this is the template test in s2i: https://github.com/redhat-developer/s2i-dotnetcore/blob/master/2.1/build/test/newtemplate/.s2i/bin/assemble
