### ISSUE TITLE
Add arm64, ppc64le and s390x to CI

### ISSUE THREAD

**Issue by omajid** [redhat-developer/dotnet-regular-tests#273]
Our tests only verify that things work on x86_64 (aka x64). We don't test on other architecture. Because of that, we run into issues and have ot fix them later. We should add some test legs for those other architectures too.

**Comment by omajid** [comment]
This came up in https://github.com/redhat-developer/dotnet-regular-tests/pull/271

**Comment by omajid** [comment]
We decided to not implement this because of possible significant CI slowdown issues.

**Comment by tmds** [comment]
Closing per previous comment.
