### ISSUE TITLE
The liblttng-ust_sys-sdt.h test needs to be updated for .NET 8

### ISSUE THREAD

**Issue by omajid** [redhat-developer/dotnet-regular-tests#278]
With our .NET 8 packages, we dropped the hard dependency on lttng-ust.

We need to adjust liblttng-ust_sys-sdt.h  to take account of this.

Some things to consider:

- Should we install lttng-ust as a test dependency?
- Should we stop testing lttng-ust for .NET 8 and later?

**Comment by tmds** [comment]
> Should we stop testing lttng-ust for .NET 8 and later?

I think we want to know if the lttng tracing works, when enabled.

**Comment by omajid** [comment]
Okay. I will ask modify the test configuration to install lttng-ust (since it wont otherwise be installed) and then this test can run normally and ensure that lttng-ust works correctly.

**Comment by tmds** [comment]
Thanks!
