### ISSUE TITLE
Extend managed-symbols-available to check ASP.NET Core shared framework

### ISSUE THREAD

**Issue by tmds** [redhat-developer/dotnet-regular-tests#308]
Currently the test is only checking the .NET Core shared framework:

https://github.com/redhat-developer/dotnet-regular-tests/blob/da96d58e528e4eb58d5ba016b7a44828ddf1e68d/managed-symbols-available/test.sh#L8

It would be good to ensure symbols are also available for the ASP.NET Core shared framework.

cc @omajid @nicrowe00

**Comment by nicrowe00** [comment]
I'll take a look.
