### ISSUE TITLE
Verify pdb packaging

### ISSUE THREAD

**Issue by tmds** [redhat-developer/dotnet-regular-tests#328]
This test should check the files contained in the dotnet packages for the .NET version under test and verify the non -dbg- packages do not contain pdbs, and the -dbg- packages only contain pdbs.

This verifies the https://src.fedoraproject.org/rpms/dotnet8.0/pull-request/1 implementation and guards for regressions.

@nicrowe00 do you want to pick this up?

cc @omajid

**Comment by nicrowe00** [comment]
@tmds Absolutely, I'll take care of it.

**Comment by tmds** [comment]
Fixed by https://github.com/redhat-developer/dotnet-regular-tests/pull/334.
