### ISSUE TITLE
Document test.json properties

### ISSUE THREAD

**Issue by tmds** [redhat-developer/dotnet-regular-tests#50]
We should have some documentation (e.g. in README) about the `test.json` file that lists and explains the properties.

CC @RheaAyase

**Comment by RheaAyase** [comment]
That would be defined here: https://github.com/redhat-developer/dotnet-bunny/blob/master/README.md 
...and it is referenced from readme.md in this repo.

**Comment by tmds** [comment]
Ah, thank you. Now I know where to look.
