### ISSUE TITLE
Add badge in README for CI

### ISSUE THREAD

**Issue by 9034725985** [redhat-developer/dotnet-regular-tests#83]
Would be nice to see a badge for the azure pipelines (:

**Comment by omajid** [comment]
We have stopped using Azure Pipelines and have switched over to GitHub Actions. You can see the action runs/results directly in the GitHub UI. Does it still make any sense to add a badge for GitHub Actions?

**Comment by 9034725985** [comment]
> We have stopped using Azure Pipelines and have switched over to GitHub Actions. You can see the action runs/results directly in the GitHub UI. Does it still make any sense to add a badge for GitHub Actions?

No, I can see a green checkmark on the top. Will close. 

![Screenshot_20210901-202816_Firefox_Beta](https://user-images.githubusercontent.com/1676445/131771715-ca2bae5f-7dc5-4907-8af2-afbe04bf8a38.png)
