### ISSUE TITLE
Test PublishReadyToRun

### ISSUE THREAD

**Issue by tmds** [redhat-developer/dotnet-regular-tests#85]
As a variation of https://github.com/redhat-developer/dotnet-regular-tests/pull/81.

This is broken with 3.0 preview9, both when publishing for the _source-build target rid_ (e.g. rhel.8-x64), but also when publishing for `linux-x64`. In the latter case, the sdk wrongly assumes the `crossgen` for `linux-x64` isn't compatible with the host system (e.g. `rhel.8-x64`).

See https://github.com/dotnet/source-build/issues/1232.

**Comment by tmds** [comment]
cc @omajid @RheaAyase

**Comment by omajid** [comment]
https://github.com/redhat-developer/dotnet-regular-tests/pull/87 was merged, so I think it's safe to close this.

Feel free to re-open if anyone disagrees.
