### ISSUE TITLE
Enable sos/lldb test on RHEL 8

### ISSUE THREAD

**Issue by omajid** [redhat-developer/dotnet-regular-tests#96]
Opening an issue to make sure we don't forget about this: https://github.com/redhat-developer/dotnet-regular-tests/commit/3ab174bd8c202d8d13f9a6d305fd93ac58f29f35

**Comment by omajid** [comment]
cc @tmds

**Comment by tmds** [comment]
This doesn't crash for me on RHEL8 using .NET Core 3.0.

I had to remove this line:
https://github.com/redhat-developer/dotnet-regular-tests/blob/90d15f730671cf642945d413bb5be87f8020a794/debugging-sos-lldb-via-core/test.sh#L182
Seems like it is no longer part of the output.

I tried running against 2.1, but then I get a message 'not running compatible .NET Core runtime'. So the 'dotnet dump' tool doesn't support 2.1.
I'll re-enable the test for rhel8.
